### ISSUE TITLE
CutterRef within terminal radare2

### ISSUE THREAD

**Issue by rgnkn** [yossizap/cutterref#5]
As I generally use radare2 in the terminal and as I use it in teaching assembler, I'd like to ask if it wouldn't be a nice idea to port CutterRef to a version for usage within the terminal.

I'd be pleased to be informed if there is an alternative approach I'm not aware of.

**Comment by trufae** [comment]
Implemented in `r2pm -ci iref`. May be good to integrate iref into cutterref and rename the project to something more generic, but for now you can use it directly in the shell or within r2. See this demo video https://youtu.be/jne9e_kBS8E . So this issue can be closed
